name: Auto-merge Dependabot PRs

on:
  pull_request:
    branches:
      - develop

permissions:
  pull-requests: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    steps:
      - name: Configure date and branch name
        id: if-vars
        run: |
          YEAR=$(date +%Y)
          MONTH=$(LC_ALL=C date +%B)
          echo "branch_name=${MONTH}-${YEAR}-report" >> $GITHUB_ENV
      - name: Approve a PR
        if: ${{ github.actor == github.repository_owner && github.event.pull_request.head.ref == steps.if-vars.outputs.branch_name }}
        run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Enable auto-merge for Dependabot PRs
        if: ${{ github.actor == github.repository_owner && github.event.pull_request.head.ref == steps.if-vars.outputs.branch_name }}
        run: gh pr merge --auto --rebase "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
