name: Tests - Create Hacker News hiring table script
on:
  push:
    branches:
      - aw_test_job

jobs:
  create-table:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./

    steps:
      - uses: actions/checkout@v3

      - name: Configure date
        run: |
          YEAR=2024
          echo "YEAR=${YEAR}" >> $GITHUB_ENV
          MONTH=December
          echo "MONTH=${MONTH}" >> $GITHUB_ENV
      - name: Run create table
        run: |
          touch test.txt
          echo "Running create table" >> test.txt

      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "Add or update documents"
          # Replace 'your-branch-name' with the name of the branch you want to create
          git push origin HEAD:your-branch-name

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Update documents"
          title: "Update Documents"
          body: "This is an auto-generated PR with document updates"
          branch: "your-branch-name" # The same branch name used in the git push command
          delete-branch: true # Set to true to delete the branch after merge
          draft: false
